name: Caller Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-dynamic-runner-assignment:
    runs-on: ubuntu-latest
    
    steps:
    - name: run-dynamic-runner-assignment
      id: set-runner
      uses: ganesh770924/Github-Reusable-actions/.github/workflows/dynamic-runner-assignment.yml@main
      with:
        repo: ${{ github.repository }}
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
    
      
  # checkout-code:
  #   # needs: call-dynamic-runner-assignment
  #   uses: ganesh770924/Github-Reusable-actions/.github/workflows/checkout-code.yaml@main
  #   # with:
  #   #   runner: ${{ needs.call-dynamic-runner-assignment.outputs.runner }}

  # setup-jdk:
  #   needs: checkout-code
  #   uses: ganesh770924/Github-Reusable-actions/.github/workflows/setup-jdk.yml@main
  #   with:
  #     java-version: '11'
  
  # build-with-gradle:
  #   needs: [checkout-code,setup-jdk]
  #   uses: ganesh770924/Github-Reusable-actions/.github/workflows/gradle-workflow.yml@main
  #   with:
  #     gradle-task: build
  #     java-version: '11'
      
  

  # build-with-maven:
  #   needs: setup-jdk
  #   uses: ganesh770924/Github-Reusable-actions/.github/workflows/build-with-maven.yml@main
  #   with:
  #     pom-file-path: 'pom.xml'

  # run-unit-tests:
  #   needs: build-with-maven
  #   uses: ganesh770924/Github-Reusable-actions/.github/workflows/run-unit-tests.yml@main

  # login-docker-hub:
  #   needs: run-unit-tests
  #   uses: ganesh770924/Github-Reusable-actions/.github/workflows/login-docker-hub.yml@main
  #   with:
  #     docker_username: ${{ secrets.DOCKER_USERNAME }}
  #     docker_password: ${{ secrets.DOCKER_PASSWORD }}

  # build-push-docker:
  #   needs: login-docker-hub
  #   uses:  ganesh770924/Github-Reusable-actions/.github/workflows/build-push-docker.yml@main
  #   # with:
  #   #   docker_username: ${{ secrets.DOCKER_USERNAME }}
  #   #   docker_password: ${{ secrets.DOCKER_PASSWORD }}
